prompt_prefix = "/$SHPOOL_SESSION_NAME/ ${VIRTUAL_ENV_PROMPT:+(${VIRTUAL_ENV_PROMPT})} "
shell = "bash"
session_restore_mode = { lines = 10000 }

[[keybinding]]
binding = "Ctrl-b d"
action = "detach"
